const jwt = require("jsonwebtoken");
const config = require("../Config/Keys");
const {promisify} = require("util");
/**
 *
 * @returns {String,String} - Token: for authentication and ExpiredIn: The time at which the token will be expired.
 */
exports.signToken = (id) => {
	return jwt.sign({
		id: id
	}, config.jwtSecret, {expiresIn: config.jwtExpiresIn});
};
/**
 *
 * @param {String} token  - Authentication token provided from user.
 * @returns {String} Id /null  - if user with the provided token exists it will return user id else it will return null
 */
exports.getUserId = async (token) => { // ? Verifying the token is generated by this our api.
	const {id, iat} = await promisify(jwt.verify)(token, config.jwtSecret);
	return id;
};
